import type { ReactNode } from "react";
import "./globals.css";

export const metadata = {
  title: "Ana Maria Ayerbe",
   icons: {
    icon: [
      { url: "/avatar.png", sizes: "any" },
      { url: "/avatar.png", type: "image/png" },
    ],
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
